[imdb]
BaseURL             = "https://datasets.imdbws.com/"
Files = ["name.basics", "title.akas", "title.basics", "title.crew", "title.episode", "title.principals", "title.ratings"]

[database]
server = "127.0.0.1"
port = 5433
user = "postgres"
password = "admin"
dbname = "imdb"
sslmode = "disable"

[server]
bind = "0.0.0.0"
port = 3000

[fs]
tempdir = ""